version: '3.10'

services:
  backend:
    build: .
    container_name: ascii_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

  frontend:
    build: ./ascii_interface
    container_name: ascii_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000